---
# This role will likely fail if not run as root.
apigee_become_user: root

apigee_tls_qs_keystore_type: jks
apigee_tls_qs_keystore_dest: /opt/apigee/customer/keystore-qs.jks
apigee_tls_qs_keystore_validity: 7300

# Set these for an existing keystore
apigee_tls_qs_keystore_src:
apigee_tls_qs_keystore_keyalias: '{{ ansible_fqdn }}'
apigee_tls_qs_keystore_password: '{{ apigee_admin_password | default("Apigee11") }}'

apigee_tls_qs_port: 18083
apigee_tls_qs_properties_path: /opt/apigee/customer/application/qpid-server.properties
apigee_tls_qs_plaintext_disabled: false
