---
- block:

  - name: Check for message processor
    stat:
      path: /opt/apigee/edge-message-processor
    register: apigee_mp_path

  - block:

    - import_role:
        name: apigee-tls-keystore
      vars:
        - apigee_tls_keystore_type: '{{ apigee_tls_mp_keystore_type }}'
        - apigee_tls_keystore_dest: '{{ apigee_tls_mp_keystore_dest }}'
        - apigee_tls_keystore_validity: '{{ apigee_tls_mp_keystore_validity }}'
        - apigee_tls_keystore_src: '{{ apigee_tls_mp_keystore_src }}'
        - apigee_tls_keystore_keyalias: '{{ apigee_tls_mp_keystore_keyalias }}'
        - apigee_tls_keystore_password: '{{ apigee_tls_mp_keystore_password }}'

    - name: Restart message processor
      command: /opt/apigee/apigee-service/bin/apigee-service edge-message-processor restart

    - name: Wait for message processor to be ready
      command: /opt/apigee/apigee-service/bin/apigee-service edge-message-processor wait_for_ready

    when: apigee_mp_path.stat.exists

  - name: Stop router
    command: removes=/opt/apigee/edge-router /opt/apigee/apigee-service/bin/apigee-service edge-router stop

  - name: Start router
    command: removes=/opt/apigee/edge-router /opt/apigee/apigee-service/bin/apigee-service edge-router start

  - name: Wait for router to be ready
    command: removes=/opt/apigee/edge-router /opt/apigee/apigee-service/bin/apigee-service edge-router wait_for_ready

  become: true
  become_user: '{{ apigee_become_user }}'
