---
- name: set devportal properties
  lineinfile:
    dest: /opt/apigee/customer/application/drupal-devportal.properties
    regexp: "^{{ item.key }}=.*"
    line: "{{ item.key }}={{ item.value }}"
    create: true
    owner: apigee
    group: apigee
    mode: 0644
  loop:
  - key: conf_devportal_nginx_listen_port
    value: "{{ apigee_devportal_port }}"
  - key: conf_devportal_ssl_block
    value: "ssl on; ssl_certificate {{ apigee_devportal_ssl_crt }}; ssl_certificate_key {{ apigee_devportal_ssl_key }}; ssl_protocols TLSv1.2;"
  - key: conf_devportal_http_https_redirect
    value: ""
  - key: conf_devportal_fastcgi_https
    value: "fastcgi_param HTTPS on; fastcgi_param HTTP_SCHEME https;" 
  register: devportal