---
- hosts: apigee_cluster
  become: yes
  vars:
    reboot: false
  tasks:
  - name: cp ca.crt
    copy:
      src: ssl/ca.crt
      dest: /etc/pki/ca-trust/source/anchors
      owner: root
      group: root
      mode: '0644'

  - name: update-ca-trust
    shell: update-ca-trust extract   
    


