---
- hosts: apigee
  become: yes
  serial: 1
  roles:
  - { name: apigee-backup, apigee_component: apigee-cassandra }
  - { name: apigee-backup, apigee_component: apigee-zookeeper }
  - { name: apigee-backup, apigee_component: apigee-postgresql }
  - { name: apigee-backup, apigee_component: apigee-openldap }
  - { name: apigee-backup, apigee_component: apigee-qpidd } 
  - { name: apigee-backup, apigee_component: apigee-postgresql }  
  - { name: apigee-backup, apigee_component: edge-management-server }
  - { role: apigee-backup, apigee_component: edge-router }
  - { name: apigee-backup, apigee_component: edge-message-processor }
  - { role: apigee-backup, apigee_component: edge-postgres-server }
  - { role: apigee-backup, apigee_component: edge-qpid-server }
  - { role: apigee-backup, apigee_component: apigee-sso}
  - { role: apigee-backup, apigee_component: edge-management-ui }
  - { role: apigee-backup, apigee_component: edge-ui}



