---
apigee_tmp_dir: /tmp/apigee
apigee_clean_up: true
apigee_scan_ports: false
apigee_always_run_setup: false

apigee_installation_path: /opt
apigee_edge_installation_path: '{{ apigee_installation_path }}/apigee'
apigee_nginx_installation_path: '{{ apigee_installation_path }}/nginx'

apigee_cluster_hostname: '{{ inventory_hostname }}'

apigee_admin_email: opdk@apigee.com
apigee_admin_password: Apigee11

apigee_postgresql_password: '{{ apigee_admin_password }}'

# Set this to enable mail.
apigee_smtp_host:
apigee_smtp_port: 25
apigee_smtp_user:
apigee_smtp_password:
apigee_smtp_ssl: false
apigee_smtp_mail_from: noreply@apigee.com

apigee_enable_autostart: true

apigee_organization_name: apigee

### Developer Portal ###
apigee_devportal_postgresql_host:

# PostgreSQL admin credentials.
apigee_dp_postgresql_username: apigee
apigee_dp_postgresql_password: '{{ apigee_postgresql_password }}'

# Developer portal database name and credentials.
apigee_dp_db_name: devportal
apigee_dp_db_username: devportal
apigee_dp_db_password: '{{ apigee_postgresql_password }}'

# PHP settings.
apigee_dp_php_port: 8888

# SMTP settings.
apigee_dp_smtp_host: '{{ apigee_smtp_host or "localhost" }}'
apigee_dp_smtp_port: '{{ apigee_smtp_port }}'
apigee_dp_smtp_user: '{{ apigee_smtp_user }}'
apigee_dp_smtp_password: '{{ apigee_smtp_password }}'
apigee_dp_smtp_ssl: '{{ apigee_smtp_ssl }}'

# Developer portal admin user.
apigee_dp_admin_firstname: Apigee
apigee_dp_admin_lastname: OPDK
apigee_dp_admin_username: opdk
apigee_dp_admin_email: '{{ apigee_admin_email }}'
apigee_dp_admin_password: '{{ apigee_admin_password }}'

apigee_ms_scheme: http
apigee_msip: 
apigee_mgmt_port: 8080

# Management API connection information.
apigee_dp_ms_organization_name: '{{ apigee_organization_name }}'
apigee_dp_ms_protocol: '{{ apigee_ms_scheme }}'
apigee_dp_ms_port: '{{ apigee_mgmt_port }}'
apigee_dp_ms_admin_email: '{{ apigee_admin_email }}'
apigee_dp_ms_admin_password: '{{ apigee_admin_password }}'


apigee_sso_public_url_scheme: http
apigee_sso_public_url_hostname: "{{ ansible_default_ipv4.address }}"
apigee_sso_public_url_port: 9099

apigee_sso_admin_name: ssoadmin
apigee_sso_admin_secret: "{{ apigee_edge_password }}"

apigee_devportal_sso_enabled: "y"

apigee_portalcli_sso_client_name: devportal
apigee_portalcli_sso_client_secret: "{{ apigee_edge_password }}"
apigee_portalcli_sso_client_overwrite: "y"
