---
- name: Create {{ apigee_sso_tomcat_keystore_path }}
  file:
    path: '{{ apigee_sso_tomcat_keystore_path }}'
    state: directory
    owner: apigee
    group: apigee
    mode: 0755

- import_role:
    name: apigee-tls-keystore
  vars:
    - apigee_tls_keystore_type: '{{ apigee_tls_sso_keystore_type }}'
    - apigee_tls_keystore_dest: '{{ apigee_tls_sso_keystore_dest }}'
    - apigee_tls_keystore_validity: '{{ apigee_tls_sso_keystore_validity }}'
    - apigee_tls_keystore_src: '{{ apigee_tls_sso_keystore_src }}'
    - apigee_tls_keystore_keyalias: '{{ apigee_tls_sso_keystore_keyalias }}'
    - apigee_tls_keystore_password: '{{ apigee_tls_sso_keystore_password }}'