---
- block:

  - name: Check for newEdge UI
    stat:
      path: /opt/apigee/edge-management-ui
    register: apigee_edgeui_path

  - block:

    - import_role:
        name: apigee-ssl
      vars:
        apigee_ssl_key: "{{ apigee_ssl_edgeui_key }}"
        apigee_ssl_crt: "{{ apigee_ssl_edgeui_crt }}"
        apigee_ssl_dest_path: "{{ apigee_imanagement_ui_tls_path }}"
        apigee_ssl_dest_key: server.key
        apigee_ssl_dest_crt: server.crt   

    - name: edge-management-ui restart
      command: /opt/apigee/apigee-service/bin/apigee-service edge-management-ui restart

    when: apigee_edgeui_path.stat.exists

  become: true
  become_user: '{{ apigee_become_user }}'
