---
- import_role:
    name: apigee-ssl
  vars:
    apigee_ssl_key: "{{ apigee_ssl_monit_key }}"
    apigee_ssl_crt: "{{ apigee_ssl_monit_crt }}"
    apigee_ssl_dest_path: "{{ apigee_monit_ssl_path }}"
    apigee_ssl_dest_key: "{{ apigee_ssl_monit_dest_key }}"
    apigee_ssl_dest_crt: "{{ apigee_ssl_monit_dest_crt }}" 

- block:
  - name: cat key and cert
    shell:
      cat {{ apigee_monit_ssl_path }}/{{ apigee_ssl_monit_dest_key }} {{ apigee_monit_ssl_path }}/{{ apigee_ssl_monit_dest_crt }}
    register: pem_content

  - name: create pem
    copy:
      dest: "{{ apigee_monit_ssl_path }}/{{ apigee_ssl_monit_dest_pem }}"
      content: "{{ pem_content.stdout }}"
      owner: apigee
      group: apigee
      mode: 0600

#- block:
#  - name: create pem
#    file:
#      path: "{{ apigee_monit_ssl_path }}/{{ apigee_ssl_monit_dest_pem }}"
#      state: touch
#      owner: apigee
#      group: apigee
#      mode: 0600

#  - name: merge ssl to pem  
#    shell: |
#      cat {{ apigee_monit_ssl_path }}/{{ apigee_ssl_monit_dest_key }} > {{ apigee_monit_ssl_path }}/{{ apigee_ssl_monit_dest_pem }}
#      cat {{ apigee_monit_ssl_path }}/{{ apigee_ssl_monit_dest_crt }} >> {{ apigee_monit_ssl_path }}/{{ apigee_ssl_monit_dest_pem }}

