---
apigee_tmp_dir: /tmp/apigee
apigee_clean_up: true
apigee_scan_ports: false
apigee_always_run_setup: false

apigee_installation_path: /opt
apigee_edge_installation_path: '{{ apigee_installation_path }}/apigee'
apigee_nginx_installation_path: '{{ apigee_installation_path }}/nginx'

apigee_cluster_hostname: '{{ inventory_hostname }}'

apigee_admin_email: opdk@apigee.com
apigee_admin_password: Apigee11

apigee_postgresql_user: apigee
apigee_postgresql_password: "{{ apigee_edge_password }}"

apigee_mo_postgresql_host:
apigee_mo_postgresql_user: mo
apigee_mo_postgresql_password: "{{ apigee_postgresql_password }}"


apigee_cassandra_cluster_name: Apigee
apigee_cassandra_authentication: true
apigee_cassandra_username: cassandra
apigee_cassandra_password: '{{ apigee_admin_password }}'
apigee_cassandra_default_password: cassandra

# Leave blank to disable mail.
apigee_smtp_host:
apigee_smtp_port: 25
apigee_smtp_user:
apigee_smtp_password:
apigee_smtp_ssl: false
apigee_smtp_mail_from: noreply@apigee.com

apigee_enable_autostart: true

apigee_port_http_ms: 8080

