---
- name: Set setup.sh path
  set_fact:
    apigee_setup_path: /opt/apigee/apigee-setup/bin/setup.sh

- name: force setup to run
  file:
    path: /opt/apigee/customer/.setup-finished/edge
    state: absent
  when: apigee_always_run_setup == true

- name: create setup flags directory
  file:
    path: /opt/apigee/customer/.setup-finished/edge
    state: directory
    owner: apigee
    group: apigee
    mode: 0755

- import_tasks: setup-ds.yml
  when: apigee.profiles | intersect(('ds', 'sa', 'aio'))

- name: Setup LDAP servers
  shell: '{{ apigee_setup_path }} -f {{ apigee_edge_response_path }} -p ld && touch /opt/apigee/customer/.setup-finished/edge/ld'
  args:
    creates: /opt/apigee/customer/.setup-finished/edge/ld
  when: ('ld' in apigee.profiles)

- name: Setup Management servers
  shell: sleep {{ apigee.ms_pause }}; {{ apigee_setup_path }} -f {{ apigee_edge_response_path }} -p ms && touch /opt/apigee/customer/.setup-finished/edge/ms
  args:
    creates: /opt/apigee/customer/.setup-finished/edge/ms
  when: ('ms' in apigee.profiles)

# For clustered installations.
- import_tasks: setup-ds-keyspace.yml
  when: ('ds' in apigee.profiles)

- name: Set Message Processor limits
  copy:
    src: 99-message-processor.conf
    dest: /etc/security/limits.d/99-message-processor.conf
    owner: root
    group: root
    mode: 0644
  when:
    - apigee_set_limits
    - apigee.profiles | intersect(('mp', 'rmp', 'sa', 'aio'))

- import_tasks: installation-path.yml
  when: apigee.profiles | intersect(('r', 'rmp', 'sa', 'aio'))

- name: Setup gateways and queues
  shell: '{{ apigee_setup_path }} -f {{ apigee_edge_response_path }} -p {{ item }} && touch /opt/apigee/customer/.setup-finished/edge/{{ item }}'
  args:
    creates: /opt/apigee/customer/.setup-finished/edge/{{ item }}
  loop: '{{ apigee.profiles }}'
  when: item in ('r', 'mp', 'rmp', 'qs', 'sa', 'aio')

# For standalone installations.
- import_tasks: setup-ds-keyspace.yml
  when: apigee.profiles | intersect(('sa', 'aio'))

- import_tasks: setup-ps.yml

# Developer Portal autostart script doesn't work
- name: Check for Developer Portal
  stat:
    path: /opt/apigee/apigee-drupal-devportal
  register: apigee_drupal_path

- name: Enable automatic start
  command: /opt/apigee/apigee-service/bin/apigee-all enable_autostart
  when: apigee_enable_autostart
  register: apigee_autostart_result
  failed_when: apigee_autostart_result.rc != 0 and not apigee_drupal_path.stat.exists
