---
apigee_installation_path: /opt
apigee_edge_installation_path: '{{ apigee_installation_path }}/apigee'
apigee_nginx_installation_path: '{{ apigee_installation_path }}/nginx'

apigee_ms_scheme: http
apigee_msip: 
apigee_mgmt_port: 8080

apigee_edgeui_enable_unified_ui: "y"

apigee_management_ui_scheme: http
apigee_management_ui_ip: "{{ ansible_default_ipv4.address }}"
apigee_management_ui_port: 3001

apigee_management_ui_app_env: "{{ apigee_environment_name }}"

apigee_management_ui_sso_csrf_secret: "{{ apigee_edge_password }}"
apigee_management_ui_sso_csrf_expiration_hours: 24

apigee_management_ui_sso_strict_transport_security_age_hours: 8760

apigee_management_ui_sso_enabled: "y"
apigee_management_ui_sso_client_id: edgeui
apigee_management_ui_sso_client_secret: "{{ apigee_edge_password }}"
apigee_management_ui_sso_client_overwrite: "y"


apigee_shoehorn_scheme: http
apigee_shoehorn_port: 9000  

apigee_classic_ui_scheme: http
apigee_classic_ui_ip: "{{ apigee_msip }}"
apigee_classic_ui_port: 9000

apigee_edge_sso_enabled: "y"

apigee_edgeui_sso_client_name: edgeui
apigee_edgeui_sso_client_secret: "{{ apigee_edge_password }}"
apigee_edgeui_sso_client_overwrite: "y"

apigee_sso_public_url_scheme: http
apigee_sso_public_url_hostname: "{{ ansible_default_ipv4.address }}"
apigee_sso_public_url_port: 9099

apigee_management_ui_skip_verify: y

apigee_sso_admin_name: ssoadmin
apigee_sso_admin_secret: "{{ apigee_edge_password }}"

apigee_smtp_host:
apigee_smtp_port: 25
apigee_smtp_user:
apigee_smtp_password:
apigee_smtp_ssl: false
apigee_smtp_mail_from: noreply@apigee.com

apigee_enable_autostart: true