---
# This role will likely fail if not run as root.
apigee_become_user: root

apigee_tls_router_keystore_type: jks
apigee_tls_router_keystore_dest: /opt/apigee/customer/keystore-router.jks
apigee_tls_router_keystore_validity: 7300

# Set these for an existing keystore
apigee_tls_router_keystore_src:
apigee_tls_router_keystore_keyalias: '{{ ansible_fqdn }}'
apigee_tls_router_keystore_password: '{{ apigee_admin_password | default("Apigee11") }}'

apigee_tls_router_port: 18081
apigee_tls_router_properties_path: /opt/apigee/customer/application/router.properties
apigee_tls_router_plaintext_disabled: false
