---
- name: Set setup.sh path
  set_fact:
    apigee_setup_path: /opt/apigee/apigee-setup/bin/setup.sh 

- name: force setup to run
  file:
    path: /opt/apigee/customer/.setup-finished/edgeui
    state: absent
  when: apigee_always_run_setup == true

- name: create setup flags directory
  file:
    path: /opt/apigee/customer/.setup-finished/edgeui
    state: directory
    owner: apigee
    group: apigee
    mode: 0755

- name: Install sendmail
  package:
    name: sendmail
    state: present

- name: Setup apigee edgeui servers
  shell: '{{ apigee_setup_path }} -p ue -f {{ apigee_edgeui_response_path }} && touch /opt/apigee/customer/.setup-finished/edgeui/edgeui'
  args:
    creates: /opt/apigee/customer/.setup-finished/edgeui/edgeui

- name: Enable automatic start
  command: /opt/apigee/apigee-service/bin/apigee-all enable_autostart
  when: apigee_enable_autostart
  ignore_errors: yes